clickatell:
  humanized_name: 'Clickatell channel'
  attributes:
    - name: protocol
      value: sms
      user: false
    - name: configuration
      attributes:
        - name: username
        - name: password
          type: password
        - name: api_id
          label: API ID
        - name: from
        - name: network
          type: enum
          options:
            - value: '61'
              display: '+61'
            - value: '44a'
              display: '+44 [A]'
            - value: '46'
              display: '+46'
            - value: '49'
              display: '+49'
            - value: '45'
              display: '+45'
            - value: '44b'
              display: '+44 [B]'
            - value: 'usa'
              display: 'USA shortcode'
        - name: concatenation
        - name: incoming_password
          type: password
          label: Incoming password (to use for the callback URLs)

dtac:
  humanized_name: 'DTAC channel'
  attributes:
    - name: protocol
      value: sms
      user: false
    - name: configuration
      attributes:
        - name: username
        - name: password
          type: password

ipop:
  humanized_name: 'I-POP channel'
  attributes:
    - name: protocol
      value: sms
      user: false
    - name: configuration
      attributes:
        - name: url
          label: URL
        - name: username
          label: Username (optional)
        - name: password
          type: password
          label: Password (optional)
        - name: cid
          label: Connection ID (cid)
        - name: bid
          label: Billing Level (bid)

msn:
  humanized_name: 'MSN channel'
  attributes:
    - name: protocol
      value: msn
      user: false
    - name: configuration
      attributes:
        - name: email
        - name: password
          type: password

isms:
  humanized_name: 'Multimodem iSms channel'
  attributes:
    - name: protocol
      value: sms
      user: false
    - name: configuration
      attributes:
        - name: host
        - name: port
          type: integer
          default_value: 81
        - name: user
        - name: password
          type: password
        - name: time_zone
          type: timezone

pop3:
  humanized_name: 'POP3 channel'
  attributes:
    - name: protocol
      value: mailto
      user: false
    - name: configuration
      attributes:
        - name: host
        - name: port
          type: integer
        - name: user
        - name: password
          type: password
        - name: use_ssl
          type: boolean
          label: "Use SSL?"
        - name: remove_quoted_text_or_text_after_first_empty_line
          type: boolean

qst:
  humanized_name: 'QST client channel'
  attributes:
    - name: protocol
      value: sms
      user: false
    - name: configuration
      attributes:
        - name: url
          label: URL
        - name: user
        - name: password
          type: password

smpp:
  humanized_name: 'SMPP channel'
  attributes:
    - name: protocol
      value: sms
      user: false
    - name: configuration
      attributes:
        - name: host
        - name: port
          type: integer
        - name: user
        - name: password
          type: password
        - name: system_type
          default_value: vma
        - name: source_ton
        - name: source_npi
        - name: destination_ton
        - name: destination_npi
        - name: service_type

smtp:
  humanized_name: 'SMTP channel'
  attributes:
    - name: protocol
      value: mailto
      user: false
    - name: configuration
      attributes:
        - name: host
        - name: port
          type: integer
        - name: user
        - name: password
          type: password
        - name: use_ssl
          type: boolean
          label: "Use SSL?"

twilio:
  humanized_name: 'Twilio channel'
  attributes:
    - name: protocol
      value: sms
      user: false
    - name: configuration
      attributes:
        - name: account_sid
        - name: auth_token
        - name: from
        - name: incoming_password
          type: password
          label: Incoming password (to use for the callback URLs)

twitter:
  humanized_name: 'Twitter channel'
  attributes:
    - name: protocol
      value: twitter
      user: false

xmpp:
  humanized_name: 'XMPP channel'
  attributes:
    - name: protocol
      value: xmpp
      user: false
    - name: configuration
      attributes:
        - name: user
        - name: domain
        - name: password
          type: password
        - name: server
        - name: port
          type: integer
          default_value: 5222
        - name: resource
        - name: status
        - name: send_offline
          type: boolean
          label: Send if user is offline

