clickatell:
  humanized_name: 'Clickatell channel'
  attributes:
    - name: protocol
      value: sms
      user: false
    - name: configuration
      attributes:
        - name: user
        - name: password
          type: password
        - name: api_id
          label: API ID
        - name: from
        - name: network
          type: enum
          options:
            - value: '61'
              display: '+61'
            - value: '44a'
              display: '+44 [A]'
            - value: '46'
              display: '+46'
            - value: '49'
              display: '+49'
            - value: '45'
              display: '+45'
            - value: '44b'
              display: '+44 [B]'
            - value: 'usa'
              display: 'USA shortcode'
        - name: concatenation
        - name: incoming_password
          type: password
          humanized_name: Incoming password
          label: Incoming password (to use for the callback URLs)
        - name: cost_per_credit
          label: "Cost per credit (messages will get a 'cost' custom attribute with the value charge * cost_per_credit)"
          default_value: 1

dtac:
  humanized_name: 'DTAC channel'
  attributes:
    - name: protocol
      value: sms
      user: false
    - name: configuration
      attributes:
        - name: user
        - name: password
          type: password

ipop:
  humanized_name: 'I-POP channel'
  attributes:
    - name: protocol
      value: sms
      user: false
    - name: address
      humanized_name: From address
      label: 'Address (this is usually the "from" number)'
    - name: configuration
      attributes:
        - name: mt_post_url
          humanized_name: Post URL
          label: Post URL
        - name: mt_post_user
          humanized_name: Username
          label: Username (optional)
        - name: mt_post_password
          type: password
          humanized_name: Password
          label: Password (optional)
        - name: cid
          label: Connection ID (cid)
        - name: bid
          label: Billing Level (bid)

msn:
  humanized_name: 'MSN channel'
  attributes:
    - name: protocol
      value: msn
      user: false
    - name: configuration
      attributes:
        - name: email
        - name: password
          type: password

multimodem_isms:
  humanized_name: 'Multimodem iSms channel'
  attributes:
    - name: protocol
      value: sms
      user: false
    - name: address
      humanized_name: From address
      label: 'Address (this is usually the "from" number)'
    - name: configuration
      attributes:
        - name: host
        - name: port
          type: integer
          default_value: 81
        - name: user
        - name: password
          type: password
        - name: time_zone
          type: timezone

pop3:
  humanized_name: 'POP3 channel'
  attributes:
    - name: protocol
      value: mailto
      user: false
    - name: configuration
      attributes:
        - name: host
        - name: port
          type: integer
        - name: user
        - name: password
          type: password
        - name: use_ssl
          type: boolean
          label: "Use SSL?"
        - name: remove_quoted_text_or_text_after_first_empty_line
          type: boolean

qst_client:
  humanized_name: 'QST client channel'
  attributes:
    - name: protocol
      value: sms
      user: false
    - name: configuration
      attributes:
        - name: url
          label: URL
        - name: user
        - name: password
          type: password

smtp:
  humanized_name: 'SMTP channel'
  attributes:
    - name: protocol
      value: mailto
      user: false
    - name: configuration
      attributes:
        - name: host
        - name: port
          type: integer
        - name: user
        - name: password
          type: password
        - name: use_ssl
          type: boolean
          label: "Use SSL?"

twilio:
  humanized_name: 'Twilio channel'
  attributes:
    - name: protocol
      value: sms
      user: false
    - name: configuration
      attributes:
        - name: account_sid
        - name: auth_token
        - name: from
        - name: incoming_password
          type: password
          label: Incoming password (to use for the callback URLs)

xmpp:
  humanized_name: 'XMPP channel'
  attributes:
    - name: protocol
      value: xmpp
      user: false
    - name: configuration
      attributes:
        - name: user
        - name: domain
        - name: password
          type: password
        - name: server
        - name: port
          type: integer
          default_value: 5222
        - name: resource
        - name: status
        - name: send_offline
          type: boolean
          label: Send if user is offline

shujaa:
  humanized_name: 'Shujaa channel'
  attributes:
    - name: protocol
      value: sms
      user: false
    - name: configuration
      attributes:
        - name: shujaa_url
          default_value: http://sms.shujaa.mobi
          label: Shujaa URL
        - name: username
          label: Username (your account's username or email)
        - name: password
          type: password
          label: Password (your account's password)
        - name: shujaa_account
          type: enum
          label: Account
          options:
            - value: live
              display: Live
            - value: developer
              display: Developer
    - name: address
      label: Source (the short code or mask which will be used as the origin of this SMS)

